### ISSUE TITLE
Table format for Locality not respected

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#1204]
**Describe the bug**
The table format configured in Specify 6 for Locality is not respected in Specify 7.

**To Reproduce**
1. Configure a table format for locality in 6.
2. See in 7.

**Expected behavior**
Table format should be the same in 6 and 7.

**Screenshots**
![image](https://user-images.githubusercontent.com/37256050/159966081-df6c8e42-e21b-4965-99f7-a03e37e509a1.png)

From CSIRO:
![image](https://user-images.githubusercontent.com/37256050/159966394-1ed5701c-f8f0-43dd-8f01-14112dce3313.png)

**Desktop:**
 - OS: Windows 10
 - Browser: Edge
 - Specify 7 Version: 7.6.1

**Reported By**
CSIRO

**Comment by maxxxxxdlp** [comment]
Is that the case for all tables?
Is that the case in the query builder?

**Comment by maxxxxxdlp** [comment]
Unable to replicate when looking at the exact same record. This could have been a bug that have since been fixed in Specify 7.7.0

@grantfitzsimmons Can you please test this again? And if it happens, provide a URL to the record.

<img width="1800" alt="Screen Shot 2022-07-26 at 22 17 17" src="https://user-images.githubusercontent.com/40512816/181153179-67bbb578-eefa-4437-840d-afad3721b62c.png">
<img width="1800" alt="Screen Shot 2022-07-26 at 22 17 24" src="https://user-images.githubusercontent.com/40512816/181153188-1b4e1810-3dfb-46c4-a83c-135d4575f401.png">

**Comment by benanhalt** [comment]
The query combox defines it's own format. I think it uses the default format for the table if none is defined.

**Comment by grantfitzsimmons** [comment]
Sorry, I am still not understanding why there is a discrepancy between Specify 6 and 7 here. The QCBX format defined in Specify should apply to both versions right?

**Comment by benanhalt** [comment]
Yes. Is the discrepancy still present in the current version?

**Comment by grantfitzsimmons** [comment]
Format for the query builder is using the system default but the query combo box is using the customized formatter.

db: `ANFC`

**Comment by benanhalt** [comment]
I created a new issue #2270 for the above since it has to do with the query builder results and may be separate from this issue.

**Comment by benanhalt** [comment]
It seems like that bug also affects the query cbx. When searching you see the results formatted as they are in the query builder results, and when you select one, it appears in that format in the unsaved form. The fix for that bug should resolve both.
