### ISSUE TITLE
[a11y] Mapper reccomending NOT MAPPED in WB

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#1302]
**Describe the bug**
**NOT MAPPED** is recommended & can precede valid mappings

**To Reproduce**
1. Go to the WB mapper
2. See error when recommending children of Agents, in this case the collectors table
3. You can use the Full Data Import sample from the `newmexico` db to test this

**Expected behavior**
Not mapped should not be a valid option before a child

**Screenshots**
![image](https://user-images.githubusercontent.com/37256050/164474121-f03d54c5-4360-47d1-85aa-687eeebe5ac0.png)

**Desktop (please complete the following information):**
 - edge, macOS

**Comment by grantfitzsimmons** [comment]
![image](https://user-images.githubusercontent.com/37256050/164474605-f73773ef-f9c9-48b1-86a5-0506f6667ed3.png)
See duplicate Collector table

**Comment by grantfitzsimmons** [comment]
`Data Set uploaded. This Upload Plan cannot be changed`

This is not correct AFAIK

**Comment by maxxxxxdlp** [comment]
Fixed both issues.
The auto mapper issue has been fixed in cases where I found, but there may be other cases where it would happen -> need more testing.
@grantfitzsimmons I can't open WB in the newmexico database because of a server error. Can you test this data set again to see if the issues are fixed?

**Comment by grantfitzsimmons** [comment]
Presumably this is not fixed since @realVinayak was able to recreate

**Comment by grantfitzsimmons** [comment]
Cautiously I believe these issues have been resolved- but I am able to get NOT MAPPED between one table and a chosen mapping (Any, Between, etc)

**Comment by maxxxxxdlp** [comment]
Found yet another case where this happened. Should be fixed.
if you encounter any more cases, please send the URLs or the screenshots
