### ISSUE TITLE
Cannot add preparations

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#1779]
![image](https://user-images.githubusercontent.com/37256050/176451976-602e403b-b78b-4517-9ef6-22a0137435eb.png)

I am unable to add preparations in 7.7. When I use `edge`, I can add and view preparations correctly.

db: `newmexico_july22`
user: `spadmin`

**Comment by maxxxxxdlp** [comment]
It's a bug I introduced yesterday. Should be fixed now. Need to test this again.

**Comment by grantfitzsimmons** [comment]
The issue still occurs for me this morning after reloading the deployments

**Comment by maxxxxxdlp** [comment]
Looks like I forgot to push the fix for this 🤦. Sorry
Please test again
