### ISSUE TITLE
Window stuttering when switching between items when browsing in forms

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#2429]
https://user-images.githubusercontent.com/37256050/201163205-ef0da16b-51e2-42af-ac4b-a38041c3ef88.mov

https://umich-testability.test.specifysystems.org/specify/query/117/

https://umich-edge.test.specifysystems.org/specify/query/117/

Compared to `edge`

**Comment by maxxxxxdlp** [comment]
Fixed. Caused by the division pick list (rendered as a query combo box) - it isn't rendered while it is fetching data for the new resource, causing the size of the form to change.

Fixed by rendering it as a disabled field instead of not rendering it at all.

As part of testing this fix, please also do basic testing (make sure they are rendered on the form without error) for:
- The "fields" pick list on the PickList form
- The "tables" pick list on the PickList form
- The "formatters" pick list on the PickList form
- The "division" pick list on the Accession form
- Tree rank pick list

**Comment by chanulee1** [comment]
"Tables" picklist, "Fields" picklist, "Formatters" picklist rendering incorrectly on picklist form. All picklist records seem to display "Division" for these picklists, depending on picklist type. Also, the "type" of the "Department" picklist record is different between `edge` and `testability`.

`testability`:
<img alt="image" width="600px" src="https://user-images.githubusercontent.com/103299204/203635197-20110140-9bd6-4585-9b44-057e2fed996f.png"/>

`edge`:
<img alt="image" width="600px" src="https://user-images.githubusercontent.com/103299204/203635265-90221dbd-57fd-4c58-b220-1653231bb5fa.png"/>

https://umich-testability.test.specifysystems.org/specify/query/new/picklist/
https://umich-edge.test.specifysystems.org/specify/query/new/picklist/

**Comment by maxxxxxdlp** [comment]
Fixed. Looks like this bug was specific to this database, so use it when testing the fix

**Comment by chanulee1** [comment]
Seems to still happen. Also, when viewing the picklist records through "Browse In Forms", there are records that are unsaved upon navigation in both `edge` and `testability` because their size limits are set to zero. Navigating to one of these records seems to clear the "Table Name" field for all records in the set.

https://user-images.githubusercontent.com/103299204/204061912-001732cc-4f0f-4e18-a46f-26f2ed9e24f5.mp4

**Comment by maxxxxxdlp** [comment]
Looks like pick lists where showing a stale value when in Browse in Forms view and you go to a different record.

Fixed

**Comment by chanulee1** [comment]
Seems to be perpetual loading when navigate to end of set and then to second-to-last record.

https://user-images.githubusercontent.com/103299204/204924684-27bef610-d0e1-4b6f-855e-bb29bf906f0b.mp4

**Comment by chanulee1** [comment]
Is this a separate issue?

https://user-images.githubusercontent.com/103299204/204925238-29dc8628-e81d-488c-abc9-5f9b414759b1.mp4

**Comment by maxxxxxdlp** [comment]
@chanulee1 regarding the perpetual loading, could you wait for a minute to see if it loads eventually? It has to run the query and then fetch the pick list, which could take some time

**Comment by maxxxxxdlp** [comment]
Fixed the `Field Name` pick list issue. Same bug could also have happened for the `Formatter` pick list.

**Comment by melton-jason** [comment]
Form-resizing when loading a record in a recordset-like form still seems to be an issue. 
Created a Collection Object Query in `kufishnotests` and selected 105 query results then viewed in forms. 


_**Video**_

https://user-images.githubusercontent.com/64045831/205111335-b696ae8e-5a9a-44ad-abe9-99a979872c6e.mp4

Also occurred to a lighter extent in  `keherbariumvascular`. Was not able to replicate in `willemcatno`.

**Comment by maxxxxxdlp** [comment]
@melton-jason Is this also reproducible on `edge`? It probably is. If so, feel free to open a separate issue for that. The original bug here was caused by a change in testability.

Forms jumping around is wasn't fully fixed in `edge` because it's tricky - it would require fetching all of the related resources before displaying anything - while that could help in here, it would make working with forms slower.

**Comment by chanulee1** [comment]
> @chanulee1 regarding the perpetual loading, could you wait for a minute to see if it loads eventually? It has to run the query and then fetch the pick list, which could take some time

Loading for 10+ minutes before stopping. However, the perpetual loading does not happen when navigating away from the record and then navigating back to it.

https://user-images.githubusercontent.com/103299204/205234722-e1ef55de-9830-43bb-a896-9ad5646fd2c1.mp4

**Comment by chanulee1** [comment]
> Fixed the `Field Name` pick list issue. Same bug could also have happened for the `Formatter` pick list.

Appears to be fixed!

**Comment by maxxxxxdlp** [comment]
Fixed the query fetching bug. Turns out it only happened for queries when there are between 80 and 120 results

**Comment by grantfitzsimmons** [comment]
Tested & fixed!
