### ISSUE TITLE
[testability] Partial date component populated with random? date

### ISSUE THREAD

**Issue by chanulee1** [specify/specify7#2487]
Partial date component populated with seemingly random date upon cloning. Navigating to another record in the record set and then going back to the cloned record and cloning again populates date component with date of the first record that was navigated to. There is a separate issue for the save warning dialog (#2483), related?

`umich`:

https://user-images.githubusercontent.com/103299204/203657766-d671c6b9-d79d-47b1-8cd1-7db14063f7e7.mp4

https://umich-testability.test.specifysystems.org/specify/view/collectionobject/1108992/?recordsetid=9749

Slightly different behavior in `freshfish`. Can see a flicker of a different date in the partial date component but it does not actually populate the field. This date seems to depend on the last record navigated to as well:

https://user-images.githubusercontent.com/103299204/203658954-e1705b25-224d-4abd-bb93-1f7801f1ddfb.mp4

https://freshfish-testability.test.specifysystems.org/specify/view/collectionobject/61120/?recordsetid=44

**Comment by maxxxxxdlp** [comment]
https://github.com/specify/specify7/issues/2483 is fixed now and significant portion of the front-end record sets code has been rewritten (yesterday). Thus, this bug does not seem to happen for me.

Can you also try this again to see if it still happens for you?

**Comment by chanulee1** [comment]
@maxxxxxdlp Can see flicker of different date in partial date component, this time after saving. After saving and then deleting a cloned record, cloning again results in perpetual loading. The fields of this clone appear to have been carried over under the loading screen, but refreshing the page shows that the fields did not carry over and allows saving the record.


https://user-images.githubusercontent.com/103299204/204044234-1d586476-3ba9-4267-8dd2-142eb77c1efb.mp4

https://freshfish-testability.test.specifysystems.org/specify/view/collectionobject/1/?recordsetid=44

**Comment by chanulee1** [comment]
Also, opening dialogs opens the form of the record that the user is currently on in the record set, outside of the record set. Opening another takes the user back to the correct record in the record set.

https://user-images.githubusercontent.com/103299204/204045292-5341b5d9-8522-4bdf-9ad5-ab5767ccbb30.mp4

**Comment by maxxxxxdlp** [comment]
@chanulee1 opening dialog causing the record set context loss is a bug. Opened https://github.com/specify/specify7/issues/2508 for it since it is not related to the date picker issue

**Comment by maxxxxxdlp** [comment]
Fixed. Please test this again

**Comment by chanulee1** [comment]
Perpetual loading as described above seems to still occur. Now see multiple loading icons when saving a record in an RS. Is this a concern?


https://user-images.githubusercontent.com/103299204/204997089-9083c872-9bbc-4d8d-87c2-98477a598786.mp4

https://freshfish-testability.test.specifysystems.org/specify/view/collectionobject/1/?recordsetid=44

**Comment by maxxxxxdlp** [comment]
Fixed the infinite loading bug. Happened when deleting last record set item and then trying to add a new item

**Comment by maxxxxxdlp** [comment]
Fix multiple loading indicators being displayed. They were displayed while the view definition was loading

**Comment by chanulee1** [comment]
Everything fixed except for form shuffling while saving a new record to RS. Subviews appear to be taken on and off the form. Not sure if it is a big concern.


https://user-images.githubusercontent.com/103299204/205239342-b6021c42-4f5a-4470-bf47-59f6d18c5a4f.mp4

**Comment by maxxxxxdlp** [comment]
Opened https://github.com/specify/specify7/issues/2527 for this
