### ISSUE TITLE
[testability] Coordinates for locality records are always carried forward 

### ISSUE THREAD

**Issue by chanulee1** [specify/specify7#2576]
Coordinate fields for locality records are always carried forward, regardless of the carry forward config. However, the autogenerated form is working fine.

https://user-images.githubusercontent.com/103299204/206784694-c5fb0f81-fe68-40a7-a3d6-99d368ed2982.mp4

Autogenerated form:

https://user-images.githubusercontent.com/103299204/206784805-631c36df-246e-4f5e-a396-6d6bb9b59dab.mp4

https://kufishnotests-testability.test.specifysystems.org/specify/view/locality/3/?recordsetid=127

**Comment by maxxxxxdlp** [comment]
Fixed. Please test this fix with a variety of records in different databases

**Comment by chanulee1** [comment]
Issue still seems to happen. Also, saving the locality record requires pressing "save" twice.

https://user-images.githubusercontent.com/103299204/207146872-e66015e2-a061-4e48-9d16-d93d36f211d8.mp4

**Comment by maxxxxxdlp** [comment]
Turns out there were two issues here. Fixed

**Comment by melton-jason** [comment]
Seems fixed now.
Tested in `botany`
