### ISSUE TITLE
[testability] Unsaved locality records

### ISSUE THREAD

**Issue by chanulee1** [specify/specify7#2592]
Across multiple databases, there seem to be many locality records that are unsaved upon navigation.

`UOregonPaleo`:

https://user-images.githubusercontent.com/103299204/207161002-69070f5c-c25f-4651-b976-962c639a1dbc.mp4

https://uoregonpaleo-testability.test.specifysystems.org/specify/view/locality/12125/?recordsetid=1037

`willemcatno`:

https://user-images.githubusercontent.com/103299204/207161231-648a4366-189e-4100-b0ab-4a6d1519a5a5.mp4

https://willemcatno-testability.test.specifysystems.org/specify/view/locality/1/?recordsetid=1235

`kufishnotests`:

https://user-images.githubusercontent.com/103299204/207161943-e3c9bde6-2ab2-44b0-97b2-cf6bf8dbb97a.mp4

https://kufishnotests-testability.test.specifysystems.org/specify/view/locality/1/?recordsetid=127

**Comment by maxxxxxdlp** [comment]
Fixed

**Comment by chanulee1** [comment]
Seems to still happen. Reloading page resets the save.


https://user-images.githubusercontent.com/103299204/207169034-e50b5340-b5cd-4a2d-b4e1-38598f13e997.mp4

**Comment by maxxxxxdlp** [comment]
Separate bug. Fixed

**Comment by melton-jason** [comment]
The issue mostly pops up again when a new record is added to a record set and then deleted. 

To (Consitently) Reproduce:
- Add and save a new locality to [recordset_123](https://coldfish-testability.test.specifysystems.org/specify/view/locality/82/?recordsetid=123)
- Delete the new locality
- Records that now suffer from the bug:
  - https://coldfish-testability.test.specifysystems.org/specify/view/locality/81/?recordsetid=123
  - https://coldfish-testability.test.specifysystems.org/specify/view/locality/62/?recordsetid=123
  - https://coldfish-testability.test.specifysystems.org/specify/view/locality/51/?recordsetid=123
  - https://coldfish-testability.test.specifysystems.org/specify/view/locality/47/?recordsetid=123
  - ... and others


NOTE:
- The method above _always_ seems to reproduce this bug. Otherwise, it was very inconsistent as to whether the bug would affect the records or not. 

- When navigating to the record set through a direct link, the bug _never_ occured, but sometimes did when navigating though the `Record Sets` header. 

- When the record set is completely navigated away from and then reopened, the bug (sometimes) no longer affects the records. 

I could not reproduce this bug on any other databases.
