### ISSUE TITLE
Paleo Context cannot be saved on the form

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#2785]
https://kuvertpaleo11123-edge.test.specifysystems.org/specify/view/collectionobject/134579/

user: `s753m969` and `spinvertpaleoadmin`

<img width="1190" alt="image" src="https://user-images.githubusercontent.com/37256050/211884390-92e4cacc-7a42-4c8a-9008-0139aced7afe.png">

After creating a new Paleo Context record, the Save button is not triggered.

If you make a change elsewhere on the form, the save button is triggered and you can save. It reloads giving the appearance that the Paleo Context data is saved, but after reloading, it is not.

**Comment by grantfitzsimmons** [comment]
https://user-images.githubusercontent.com/37256050/217918170-070105c8-325b-414c-8f02-3947bafdb24a.mov

**Comment by maxxxxxdlp** [comment]
Bug affected all -to-one dependent relationships that are displayed in a form table
Bug present since 7.7.0
Fixed

**Comment by specifysoftware** [comment]
This issue has been mentioned on **Specify Community Forum**. There might be relevant details there:

https://discourse.specifysoftware.org/t/specify-7-8-7-release-announcement/1079/1

**Comment by grantfitzsimmons** [comment]
The Ohio State University is reporting that the last fix did not solve their issue.

They said the following:

> It looks like the stratigraphic context is still not saving.

**Comment by maxxxxxdlp** [comment]
Should either ask them for more details, or someone should test this again to see what's not working

**Comment by grantfitzsimmons** [comment]
We need to test on the following database:

https://osuorton3823-latest.test.specifysystems.org/accounts/login/?next=/specify/

I don't believe any testing was done on their DB last time

**Comment by melton-jason** [comment]
I was not able to replicate this bug on https://osuorton3823-latest.test.specifysystems.org/accounts/login/?next=/specify/ for either the Chronostratigraphy or Lithostratigraphy fields from CollectionObject -> CollectingEvent ->  Paleocontext.

You may need additional information into how they produced this bug

**Comment by maxxxxxdlp** [comment]
@grantfitzsimmons please ask for more information as to what's not working

**Comment by grantfitzsimmons** [comment]
Not able to replicate. Will close.

**Comment by grantfitzsimmons** [comment]
UMich mentioned this as an issue again. Need to verify. @bronwyncombs can you try this again on a paleo database?

db is `ku_vertpaleo_1_11_23`

**Comment by emenslin** [comment]
Cannot reproduce, I'm going to close this again
