### ISSUE TITLE
Instalation problem

### ISSUE THREAD

**Issue by InfoBio** [specify/specify7#299]
I'm in the step where the front end specify is generated, but gives warning reports, not know if you have reports of this kind and what i can be done in that case . I attached the image of the message
![screenshot from 2016-09-07 10-42-40](https://cloud.githubusercontent.com/assets/9012963/18321425/28b2e290-74eb-11e6-8dd0-91b0e0c710a0.png)

**Comment by benanhalt** [comment]
Those warnings are normal. There is a new release of [Hands On Table](https://github.com/handsontable/handsontable/releases/tag/0.24.2) that should fix them, but we need to make sure it works with Specify before we update.

**Comment by InfoBio** [comment]
Thank you, I resolved that issue too, however when I generate the front end
and restart the apache I still see the home page specify7. if by chance you
can not have a different manual instructions are on the web (
https://github.com/specify/specify7) to see if I'm skipping a step
installation.

2016-09-07 11:27 GMT-06:00 Ben Anhalt <notifications@github.com>:

**Comment by besi** [comment]
@InfoBio: Could you elaborate how you fixed that issue so that other members (such as myself) could benefit from your insights?
