### ISSUE TITLE
`NS_ERROR_FAILURE` when attempting to generate label

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#3115]
[Specify 7 Crash Report - 2023-03-08T03 34 15.722Z.txt](https://github.com/specify/specify7/files/10916946/Specify.7.Crash.Report.-.2023-03-08T03.34.15.722Z.txt)

https://purdueherbaria11023-edge.test.specifysystems.org/specify/view/collectionobject/167304/

I am unable to run a label for a Collection Object on either `v7.8.4` or `edge`.`

**Steps to Recreate:**
1. Go to the linked record above (`/view/collectionobject/167304/`) in the `purdueherbaria` db
2. Click on the "generate label" button on the bottom right hand side of the form
3. Click on `TYPE labels MARGINS`

```
[Exception... "Failure"  nsresult: "0x80004005 (NS_ERROR_FAILURE)"  location: "JS frame :: https://purdueherbaria11023-edge.test.specifysystems.org/static/js/main.88058465e6734808d152.bundle.js :: 99147/U/< :: line 2"  data: no]
```

**Comment by maxxxxxdlp** [comment]
This could be a Firefox bug - https://bugzilla.mozilla.org/show_bug.cgi?id=941146

Though, the bug doesn't happen for me (in Firefox Developer Edition):
<img width="1800" alt="Screenshot 2023-03-08 at 08 42 50" src="https://user-images.githubusercontent.com/40512816/223743288-2f045ada-5a8e-4203-a780-f8759569de3b.png">

Doesn't happen in Chrome either

The stack trace is minifed, and the js file no longer exists, so can't tell where the exception occurred

**Comment by grantfitzsimmons** [comment]
I can still recreate this every time on Firefox Developer Edition. I cannot recreate in Chrome.

**Comment by grantfitzsimmons** [comment]
Happened today on the `workshop` Specify Cloud instance on `edge`

**Comment by grantfitzsimmons** [comment]
Reported by Laura at University of Wyoming

**Comment by maxxxxxdlp** [comment]
From @carlosmbe:

> **Describe the bug** This is a quite the strange bug. I don't understand what's causing it so please forgive the rather vague explanations.
> 
> Talk to @melton-jason for more details.
> 
> **To Reproduce** Steps to reproduce the behavior:
> 
> 1. Go to `Clean NHMD` Log in as `petrifiedroadkill` and go to the `NHMD Amber` Collection
> 2. Find the first loan created in it. Namely `Loan: 2023-EN-001` or just use the link below
> 3. Make some changes or just clone
> 4. Experiment with either Generate Invoice on Save being on/off
> 5. See error
> 
> Link to loan cleannhmdtest030823copy-v79-dev.test.specifysystems.org/specify/view/loan/224/
> 
> Make up sure you have pop ups enabled on the page.
> 
> One of three things could happen when saving the loan:
> 
> 1. It works
> 2. Report Query Returned No Results
> 3. An NS_Error is thrown
> 
> **Expected behavior** It always works
> 
> **Beautiful Pictures**
> 
> <img alt="Screenshot 2023-07-12 at 2 42 00 PM" width="339" src="https://user-images.githubusercontent.com/53784701/253084218-d13f109d-378b-49de-8bf4-58146d21edd9.png"> <img alt="Screenshot 2023-07-12 at 2 14 34 PM" width="1789" src="https://user-images.githubusercontent.com/53784701/253084206-4ffd3119-4c76-4feb-a76b-0c2504ac04ff.png">
>  Screen.Recording.2023-07-12.at.2.47.07.PM.mov 
> **Desktop:**
> 
> * OS: Mac OS
> * Browser: Chrome
> * Specify 7 Version: 7.9

**Comment by grantfitzsimmons** [comment]
> Screen.Recording.2023-07-12.at.2.47.07.PM.mov **Desktop:**
> 
> * OS: Mac OS
> * Browser: Chrome
> * Specify 7 Version: 7.9

Based on that screenshot, it is evidently Firefox, not Chrome.

**Comment by grantfitzsimmons** [comment]
@carlosmbe If this is not resolved before you return, I think this is something you should look into when we begin programming tasks :smile:

**Comment by grantfitzsimmons** [comment]
It doesn't happen if you enable pop-ups.

**Comment by maxxxxxdlp** [comment]
Does it happen at all anymore? Since it's a Firefox bug, it could have been fixed on their side by now

**Comment by grantfitzsimmons** [comment]
Yes, I tried to troubleshoot it to better understand it. It only happens when pop-ups are blocked.

https://stackoverflow.com/questions/48303223/ns-error-failure-in-firefox-on-setting-font-of-canvas-inside-a-hidden-iframe

**Comment by combs-a** [comment]
Still having this issue, had it occur in `sdnhm_herps_2_8_24` when running the Gift Invoice label, as well as on `PriPaleo_SchemaUpdated_CM_202304211540` on various Loan labels/reports. It randomly happened to fix itself on `sdnhm_herps`. Still on Firefox.
