### ISSUE TITLE
Aggregator Editor: Formatting differs between `edge` and `xml-editor` in security panel

### ISSUE THREAD

**Issue by chanulee1** [specify/specify7#3142]
https://user-images.githubusercontent.com/103299204/224115838-2239e6b1-8790-40bd-9a27-c8d80d621f3b.mp4

https://coldfish-edge.test.specifysystems.org/specify/security/user/2/

https://coldfish-xml-editor.test.specifysystems.org/specify/security/user/2/

**Comment by maxxxxxdlp** [comment]
Fixed.

The bug is because `xml-editor` branch was using pick list titles instead of picklist values when evaluating the `<switch>` condition in the formatter definition. Fixed by not formatting the condition value when evaluating the condition.

Please do more compatibility testing for different field types (i.e, field formatters, pick lists, aggregated fields)

**Comment by chanulee1** [comment]
Still appears to happen.

![image](https://user-images.githubusercontent.com/103299204/225383664-d7a1a884-dc7b-4ee0-bbc6-a821a8cc67f0.png)

**Comment by chanulee1** [comment]
Still appears to happen.

![image](https://user-images.githubusercontent.com/103299204/225384455-d6d903d2-5f88-43cf-b159-3a44ba504676.png)

**Comment by chanulee1** [comment]
Form title does not seem to be displayed.
![image](https://user-images.githubusercontent.com/103299204/232612126-46372119-ac6a-43de-ad06-3decff24543e.png)

https://coldfish-xml-editor.test.specifysystems.org/specify/security/user/2/

**Comment by maxxxxxdlp** [comment]
This bug has been fixed on production. Merged recent changes from production onto xml-editor. Should be fixed now
