### ISSUE TITLE
Going to a record set triggers a form change

### ISSUE THREAD

**Issue by realVinayak** [specify/specify7#3259]
**Describe the bug**
If you click on 'Record Sets', then I am shown the list of record sets for that user. Try going from one record set to another and I get the dialog message 'This form has not been saved' even if I didn't change anything. A major issue because I wanted to know if I accidentally changed anything or not. This is in production by the way.

**To Reproduce**
1. Click on 'Record Sets' on the menu
2. Click on any record set
3. Click on 'Record Sets' again and go to another record set
4. The dialog 'This form has not been saved.' shows up.

**Expected behavior**
Shouldn't trigger the form change. Or at least tell me what changed.

![image](https://user-images.githubusercontent.com/61122018/228246447-edc2aab1-1326-48ec-aff1-a97d323b1c18.png)

**Comment by realVinayak** [comment]
The url in the screenshot: https://osuorton3823-edge.test.specifysystems.org/

**Comment by realVinayak** [comment]
Happens in Chrome, Edge and Firefox

**Comment by maxxxxxdlp** [comment]
You have an unsaved form behind the dialog.
Opening the dialog is fine and doesn't trigger the unload protect dialog.
Actually clicking on a record set would replace the form with a record set, thus unload protect dialog is triggered to warn you about this.
Not a bug.
Though, if you think this is a UX issue, do you have suggestions on improving this?

**Comment by realVinayak** [comment]
Not showing the save dialog if there actually weren't changes! I discovered
this while on production database and thought I changed the form

**Comment by maxxxxxdlp** [comment]
>  Not showing the save dialog if there actually weren't changes

Ah, that's a separate issue, not connected to record sets.

Two bugs here:
1. When collection object is created, collection relationship is set, which triggers save blocker
2. catalogedDatePrecision is set to 1 by default, which triggers save blocker

**Comment by maxxxxxdlp** [comment]
TODO:
1. Check if the two bugs mention in https://github.com/specify/specify7/issues/3259#issuecomment-1487878114 are still reproducable on xml-editor
2. Fix them

**Comment by maxxxxxdlp** [comment]
From @bronwyncombs:

> **Describe the bug** Using the `Browse in Forms` button in query dialog through stats page requires save before moving pages.
> 
> **To Reproduce** Steps to reproduce the behavior:
> 
> 1. Go to statistics page
> 2. Click on a statistic with query attached
> 3. Click on `Browse in Forms`
> 4. Use paginators
> 5. See error
> 
> **Expected behavior** Should allow to click through forms since no edits are made.
> 
> **Screenshots**
> 
>  https://github.com/specify/specify7/assets/135047322/9b8b0b13-4cc0-4002-8eda-6eb97e8dfbb2
> **Desktop:**
> 
> * OS: macOS
> * Browser: Chrome
> * Specify 7 Version: 7.9-dev
> 
> **Database Name:** If applicable herb_rbge_3_31_23
> 
> **Reported By** Name of your institution
> 
> **Additional context** Database name or any other context about the problem here.

**Comment by bronwyncombs** [comment]
`Browse in Forms` doesn't have this issue in the main query builder, only through the stats query dialog. Do you still want these merged?

**Comment by CarolineDenis** [comment]
@maxxxxxdlp @melton-jason , 
we met with @bronwyncombs for this issue because I couldn't reproduce. We discovered that it happens only if different tabs in the browser of the stat page are opened. If we have only one time Sp7 opened there is no issue. 
What are your thoughts?

**Comment by maxxxxxdlp** [comment]
set a breakpoint on this line:

https://github.com/specify/specify7/blob/39cb18c84e94bd783fc10757b593039e683df8b8/specifyweb/frontend/js_src/lib/components/DataModel/resourceApi.js#L121

and when it hits, go up the stack to see who triggered the field change and why

there could be several different causes for this issue - would be best to fix them all

**Comment by CarolineDenis** [comment]
I cannot reproduce neither on my localhost or on the test panel. I know I saw it happening on Bronwyn's computer..

**Comment by grantfitzsimmons** [comment]
> `Browse in Forms` doesn't have this issue in the main query builder, only through the stats query dialog. Do you still want these merged?

It looks like this is not the case for me:

https://github.com/specify/specify7/assets/37256050/57cb3c1d-58be-4e3c-a1c2-5cf7d62525be

This is likely an unrelated issue that @maxxxxxdlp mentioned:

> TODO:
> 1. Check if the two bugs mentioned in the previous commend (https://github.com/specify/specify7/issues/3259#issuecomment-1487878114) are still reproducible on xml-editor
> 2. Fix them

This has been a problem for a long time (at least since Specify 7.7+) where something is set upon the form loading that makes Specify think some edit has been made when it really has not.

**Comment by bronwyncombs** [comment]
Still works for me from query builder: 

https://github.com/specify/specify7/assets/135047322/22b2dc22-848c-47eb-8421-753733493786

Only some have this issue from stats: 

https://github.com/specify/specify7/assets/135047322/8487ce79-c032-4d8e-99c1-232e89673483

This is a new instance on a different database with one tab open at a time

**Comment by CarolineDenis** [comment]
Can we reproduce it on xml?

**Comment by CarolineDenis** [comment]
@melton-jason @realVinayak @acwhite211 can one of you recreate this?

**Comment by grantfitzsimmons** [comment]
@bronwyncombs 
> Still works for me from query builder:
> 
>  `Screen.Recording.2023-07-10.at.11.47.54.AM.mov`
> 
> Only some have this issue from stats:
> 
>  `screen-recording-2023-07-10-at-113003-am_LLKnihLE.mp4`
> 
> This is a new instance on a different database with one tab open at a time

The issue is that you are testing different queries and different forms. These need to be the same to confirm whether behavior is consistent between them.

On the Preparation form, nothing is being set upon load, which doesn't prompt Specify to ask if you want to save.

On the Determination form, the date precision (presumably) is being set upon load, which prompts Specify to ask you if you want to save before you can navigate away.

This is the actual underlying issue^^^

**Comment by CarolineDenis** [comment]
Could re-create when: 
stats > Paratype > browse in forms

**Comment by grantfitzsimmons** [comment]
If this is not introduced in `v7.9`, we should move this to `v7.9.1`.

**Comment by maxxxxxdlp** [comment]
Note, that this bug could be specific to a single record and a specific form.
Note, that this bug could have many causes, but all result in a same symptom.

**Comment by maxxxxxdlp** [comment]
@CarolineDenis this line I sent is the only place where we set `resource.needSaved=true`:

https://github.com/specify/specify7/blob/39cb18c84e94bd783fc10757b593039e683df8b8/specifyweb/frontend/js_src/lib/components/DataModel/resourceApi.js#L121

But, this function in turn is called in several places (in 3 places I belive, one of which is `.set()`)

To debug this issue:
1. Find a record and a form on which you can consistently reproduce this issue (that could be either on the test panel or on localhost)
2. Set a breakpoint on the line I sent above
3. When breakpoint hits, double check that `this.specifyModel.name` (or `this.specifyTable.name` if on `xml-editor`) matches the table name you expect (i.e `CollectionObject` rather than `PickList` or `TreeDefItem` - you might see the later as those are created and edited by front-end behind the scenes, especially on initial page load)
4. Then, simply follow the stack track to see who called the `.set()` function and why and with what value and what was the previous value. See https://developer.chrome.com/docs/devtools/javascript/reference/#call-stack

**Comment by CarolineDenis** [comment]
"3.When breakpoint hits, double check that this.specifyModel.name (or this.specifyTable.name if on xml-editor) matches the table name you expect (i.e CollectionObject rather than PickList or TreeDefItem - you might see the later as those are created and edited by front-end behind the scenes, especially on initial page load)" 
The name is correct

**Comment by CarolineDenis** [comment]
@melton-jason can this be closed?

**Comment by bronwyncombs** [comment]
Encountered this today on `sdnhmpaleo_3_31_23` while using Browse in Forms for Locality records.

https://github.com/specify/specify7/assets/135047322/c9702a48-cc77-4196-b023-6811b25f6dfd

**Comment by grantfitzsimmons** [comment]
Solved by #3959

**Comment by grantfitzsimmons** [comment]
https://dbfordocskufish-v79-dev.test.specifysystems.org/specify/overlay/merge/Agent/?records=1010%2C1028%2C1069%2C1102%2C1514


https://github.com/specify/specify7/assets/37256050/f41816ba-e76b-4810-972b-67c2a1a9b3a8

Going through Determination records causes this issue for me in agent merging

**Comment by carlosmbe** [comment]
Reopened. Still present in Locality Record Sets. Happens in both https://github.com/specify/specify7/pull/3959 and https://github.com/specify/specify7/pull/3774

**Comment by carlosmbe** [comment]
https://github.com/specify/specify7/assets/53784701/b2e98580-68e3-4db5-87ba-9b923c675c70

**Comment by lexiclevenger** [comment]
This also happens when navigating through a record set created using the WorkBench.

https://github.com/specify/specify7/assets/164079735/2d799c46-2647-49f2-a054-d1e8477d2242

**Comment by emenslin** [comment]
Can recreate in edge (7.9.6) but only with one RS. There are probably other RS in other dbs that can also recreate this issue but this is what I found. Not sure why this one is different though, maybe just because it's an old WB upload? 


https://github.com/user-attachments/assets/4fc9227b-ab3f-4149-987e-2ec4512c4c7b

**Comment by emenslin** [comment]
From @bronwyncombs 

> **Describe the bug**
> A clear and concise description of what the bug is.
> 
> the 8th record in this record set specifically triggers unload protect: 
> [demofish record set ](https://sp7demofish2924-v79.test.specifysystems.org/specify/view/locality/6/?recordsetid=41)
> 
> Happens on this record set in `fwri` when you skip to the last record and go backward: 
> [fwri record set](https://fwri1924-edge.test.specifysystems.org/specify/view/locality/41941/?recordsetid=1907)
> 
> - OS: macOS
> - Browser: Chrome
> - Specify 7 Version: `v7.9`
> - Database Name: `fwri_1_9_24` and `sp7demofish_2_9_24`
> 
> **Additional context**
> 
> related issue: 
> https://github.com/specify/specify7/issues/3259
