### ISSUE TITLE
Query builder crashes when querying unmapped field

### ISSUE THREAD

**Issue by carlosmbe** [specify/specify7#3311]
**Describe the bug**
If you try to hit count while one of the fields is unmapped. An error occurs. Moreover, the stats page is no longer viewable and needs to be refreshed.

**To Reproduce**
Note: This can be done in any collection.
1. Log in as `petrifiedroadkill` in` NHMD Test` Database.
2. Go to `NHDM Amber` -> Statistics. 
3. Go to any category and pick a field. 
4. Un map any value and press count.
5. See Error

**Expected behavior**
An alert dialog saying this is not allowed or returning to the main stats page.

**Screen Recording and Crash Report**

https://user-images.githubusercontent.com/53784701/230217194-957c79c7-eca8-44e6-ba19-4759fde1cf00.mov

[Specify 7 Crash Report - 2023-04-05T21_31_58.526Z (1).txt](https://github.com/specify/specify7/files/11163292/Specify.7.Crash.Report.-.2023-04-05T21_31_58.526Z.1.txt)

Desktop:

OS: Mac OSx Ventura
Browser: Chrome
Specify 7 Version: statspage branch
Database Name:
NHMD Test

Reported By
Carlos @carlosmbe

**Comment by carlosmbe** [comment]
Update: Same error happens when query in stats with an unmapped item.

**Comment by grantfitzsimmons** [comment]
This is a standard query builder bug, not specifically related to stats page from what I can tell.

**Comment by grantfitzsimmons** [comment]
> S7 BUG: Crash when query has "NOT MAPPED" taxon
> 
> Confirmed in v7.8.5 and v7.8.10
> 
> Shown in the images below is a CO query that has "Determinations" > "Taxon" > "Species" > "NOT MAPPED".
> 
> Querying results in the error shown.
> 
> `v7.8.5`
> ![image](https://user-images.githubusercontent.com/37256050/235684705-7904cc23-f138-443d-9d7d-4165101bd486.png)
> ![image](https://user-images.githubusercontent.com/37256050/235684719-8111150a-db1e-4bb0-b577-0197f8451d39.png)
> 
> `v7.8.10`
> ![image](https://user-images.githubusercontent.com/37256050/235684754-e40ddb8f-0b97-405f-95af-8d8125098953.png)
> ![image](https://user-images.githubusercontent.com/37256050/235684767-9c0b3991-6f47-4fde-ae1f-fa98d8b64db1.png)

**Reported By:** Matthew Cruz at UMich

**Comment by maxxxxxdlp** [comment]
Fixed on the `use-dynamic-ranks` branch and the `specify-network-integration` branch. Can anyone test it on them?

**Comment by carlosmbe** [comment]
@maxxxxxdlp Error Still Present on `use-dynamic-ranks`. `specify-network-integration` Fixes this issue


[Specify 7 Crash Report - 2023-06-16T21_41_35.307Z (1).txt](https://github.com/specify/specify7/files/11776070/Specify.7.Crash.Report.-.2023-06-16T21_41_35.307Z.1.txt)
[Specify 7 Crash Report - 2023-06-16T21_41_35.307Z.txt](https://github.com/specify/specify7/files/11776071/Specify.7.Crash.Report.-.2023-06-16T21_41_35.307Z.txt)
<img width="1792" alt="Screenshot 2023-06-16 at 4 41 33 PM" src="https://github.com/specify/specify7/assets/53784701/596d3aee-2f3b-43c2-9817-8e64a074c4c9">

**Comment by maxxxxxdlp** [comment]
Does this happen on production? Because specify-network-integration branch is merged into production.
If this is fixed on production the issue can be closed

**Comment by grantfitzsimmons** [comment]
@carlosmbe  Can you try this again on production soon and close this issue if it has been resolved?

**Comment by carlosmbe** [comment]
Note to self and future testers curious if this issue should be closed. 
Until this Query in NHMD Test can run or be added to Stats Page without an issue, I'd keep it open.
https://nhmdtest030823-v79.test.specifysystems.org/specify/query/405/


https://github.com/specify/specify7/assets/53784701/9618b497-7e40-4933-9566-1ec68f09df9e

[Specify 7 Crash Report - 2023-11-16T05_57_56.569Z.txt](https://github.com/specify/specify7/files/13372859/Specify.7.Crash.Report.-.2023-11-16T05_57_56.569Z.txt)

https://github.com/specify/specify7/assets/53784701/f4465ee9-e4ba-4e13-a263-88ffd05e6a11

**Comment by emenslin** [comment]
Closing in favor of #3340 as an error is no longer thrown in either case. You can unmap parts of a query in stats and there is no error and you can save and if you try to query with the `Not Mapped Query` mentioned it throws the same error that is seen in #3340. Original query no longer exists so I had to recreate it so something could've gone wrong there however since it appears to be the same I am closing this.
