### ISSUE TITLE
Merged agent record link in notifications Loading...

### ISSUE THREAD

**Issue by bronwyncombs** [specify/specify7#3889]
**Describe the bug**
Merging an agent that was just merged causes link in notifications to load forever and send to 404 page on click.

**To Reproduce**
1. Merge an agent 
2. Merge the newly merged agent into another agent
3. Open notifications
4. See error in previous link to view agent record 

**Expected behavior**
disable link if record deleted

**Screenshots**

https://github.com/specify/specify7/assets/135047322/78bc32f1-5103-4059-856c-61543fbda736

**Desktop:**
 - macOS, Chrome, v7.9-dev 

**Database Name:** `herb_rbge_3_31_23`

**Comment by grantfitzsimmons** [comment]
Should be fixed by https://github.com/specify/specify7/pull/3906

**Comment by emenslin** [comment]
Ran into this again today, not sure if this is something a user would run into but the 404 error is bad 

https://github.com/specify/specify7/assets/150940840/adfb2814-29b1-49dc-9c4a-209150db3c42

**Comment by melton-jason** [comment]
The fixes in #3906 were actually reverted due to a merge conflict, thus this issue should still happen on `production`. 
Should be fixed in #4930!
