### ISSUE TITLE
Add support for customizing tree definitions

### ISSUE THREAD

**Issue by tlammer** [specify/specify7#598]
There is no way to edit the tree definitions in 7.  
Especially problematic when you need to add/remove a tree level.

**Comment by maxxxxxdlp** [comment]
Fixed in 07b58f91
Can't add/remote tree levels yet, but can edit all other information

**Comment by grantfitzsimmons** [comment]
Add/removing a tree level is still not at feature parity with Specify 6. I can remove Phylum when Division exists in Specify 6 where I cannot delete Phylum in 7.

**Comment by grantfitzsimmons** [comment]
Still a major point we need to solve!

**Comment by maxxxxxdlp** [comment]
Regarding full name settings change, @realVinayak discovered that Specify 7 back-end already has the code for regenerating all full names, thus we can just have we can re-enable configuring full names and just call that endpointafterward.

Adding/removing tree nodes would be trickier and require seeing what sp6 does (i.e, how does it check for enforced ranks, how does it move nodes if needed)

**Comment by grantfitzsimmons** [comment]
Brought up very often. Once again by Paul Blom

**Comment by grantfitzsimmons** [comment]
This has been requested again by NRCan

**Comment by specifysoftware** [comment]
This issue has been mentioned on **Specify Community Forum**. There might be relevant details there:

https://discourse.specifysoftware.org/t/specify-7-taxonomic-tree-editing/1633/2
